accounts/urls.py
from django.urls import path, include
from .import views

app_name = 'accounts'

urlpatterns = [
    path("register", views.register, name="register"),
    path("signin", views.signin, name="signin"),
    path("signout", views.signout, name="signout"),
]

fundraiser/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import index


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("", include('accounts.urls')),

]

home/urls.py
from django.urls import path

from . import views
app_name = 'home'


urlpatterns = [
    path('', views.index, name='index'),
    path('agent', views.agent_Faq, name='agent_Faq'),
    path('broker', views.broker_Faq, name='broker_Faq'),
    path('applynow', views.applynow, name='applynow'),
    path('contactus',views.contactUs,name='contactUs'),
    path('aboutUs',views.aboutUs, name='aboutUs'),
]

home/models.py
# from django.db import models
#
# # Create your models here.
# class propertydetails(models.Model):
#     address = forms.CharField(max_length=60)
#     city = forms.CharField()
#     sate=
#     zipcode=
#     sellername=
#     buyernam=
#     finlesaleprice=
#     clsoingdate=
#     isshortsale=

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.forms.fields import EmailField
from django.forms.forms import Form


class SignUpForm(UserCreationForm):
    fname = forms.CharField(label='First name', min_length=4, max_length=150)
    lname = forms.CharField(label='Last name', min_length=4, max_length=150)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def init(self,*args , **kwargs):
        super().init(*args , **kwargs)
        self.fields["fname"].widget.attrs.update({
            'placeholder':'First name',})
        self.fields["lname"].widget.attrs.update({
            'placeholder':'Last name',})
        self.fields["email"].widget.attrs.update({
            'placeholder':'email',})
        self.fields["password1"].widget.attrs.update({
            'placeholder':'password',})
        self.fields["password2"].widget.attrs.update({
            'placeholder':'confirm password',})
    class Meta:
        model= User
        fields=['fname', 'lname', 'email','password1','password2']

    def clean_email(self):
        email = self.cleaned_data.get("email")
        new = User.objects.filter(email=email)
        if User.objects.filter(email=email).exists() or new.count():
            raise forms.ValidationError("Email already exist")
        return email

    def clean_password2(self):
        print("pass")
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password didn't match")
        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

class LoginForm(AuthenticationForm):
    def init(self,*args , **kwargs):
        super().init(*args , **kwargs)
        self.fields["email"].widget.attrs.update({
            'required':'',
            'name':'email',
            'id':'email',
            'type':'text',
            'class':'form-input',
            'placeholder':'email',
            'maxlenght':'30',
            'minlenght':'6'
        })

        self.fields["password"].widget.attrs.update({
            'required': '',
            'name': 'password',
            'id': 'password',
            'type': 'text',
            'class': 'form-input',
            'placeholder': 'password',
            'maxlenght': '100',
            'minlenght': '6'
        })
    class Meta:
        model= User
        fields=['email', 'password']

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render,redirect
from .forms import SignUpForm, LoginForm

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log in  user
            return redirect("home:index")
    else:
        form = SignUpForm()
    return render(request, 'accounts/Register.html', {'form': form})

def signin(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        # login
        if form.is_valid():
            user = form.get_user()
            print('user')
            email = form.cleaned_data.get("email")
            # send_mail_after_registration(email)
            print(user)
            login(request, user)
            return redirect("home:index")
    else:
        form = LoginForm()
    return render(request,'accounts/login.html',{'form':form})

# def send_mail_after_registration(email):
#     subject = "You Account has been Successfully created"
#     message = f"Welocme to ENDLOS"
#     email_from = settings.EMAIL_HOST_USER
#     recipient_list = [email]
#     # send_mail(subject, message, email_from, recipient_list)

def signout(request):
    if request.method == 'POST':
        logout(request)
        return render(request,'home/index.html')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

home/views.py
from re import template
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'home/index.html')


def agent_Faq(request):
    return render(request, 'home/agentFaq.html')


def broker_Faq(request):
    return render(request, 'home/brokerFaq.html')


def applynow(request):
    return render(request, 'home/applynow.html')

def contactUs(request):
    return render(request, 'home/contactUs.html')

def aboutUs(request):
    return render(request, 'home/aboutUs.html')

templates/accounts/Register.html
{% extends "home/base.html" %}
{% load static %}


{% load crispy_forms_tags %}


{% block h %}
<!-- Basic Page Needs -->
<meta charset="utf-8">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<title>Quick Commission Advance</title>

<meta name="author" content="themesflat.com">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Theme Style -->
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

<!-- Favicon and Touch Icons  -->
<link rel="shortcut icon" href="{% static 'home/icon/favicon.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'home/icon/apple-touch-icon-158-precomposed.png' %}">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% endblock %}
{% block body %}

<!--Register-->
<section>
	<div class="container" style="padding-top: 160px;">
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST" action="{% url 'accounts:register' %}">
		{% csrf_token %}
		{{ form }}
		<button class="btn btn-primary" type="submit">Register </button>
	</form>
	<p class="text-center">If you already have an account, <a href="">login</a> instead.</p>
</div>
</div>
</section>

{% endblock %}

templates/accounts/login.html
{% extends "home/base.html" %}

{% load crispy_forms_tags %}
{% load static %}

{% block h %}
<!-- Basic Page Needs -->
<meta charset="utf-8">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<title>Quick Commission Advance</title>

<meta name="author" content="themesflat.com">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Theme Style -->
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

<!-- Favicon and Touch Icons  -->
<link rel="shortcut icon" href="{% static 'home/icon/favicon.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'home/icon/apple-touch-icon-158-precomposed.png' %}">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% endblock %}






{% block body %}

<section>
  <div class="container" style="padding-top: 160px;">
    
    <!-- Submit button -->
    <form method="POST"action="{% url 'accounts:signin' %}">
      {% csrf_token %}
      {{ form}}
      <button class="btn btn-primary" type="submit">Login</button>

      <!-- Register buttons -->
      <div class="text-center">
        <p>Not a member? <a href="{% url 'accounts:register' %}">Register</a></p>
       


      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/home/aboutUs.html
{% extends "home/base.html" %}
{% load static %}

{% block h %}
<!-- Basic Page Needs -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<title>Quick Commission Advance</title>

<meta name="author" content="themesflat.com">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Theme Style -->
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

<!-- Favicon and Touch Icons  -->
<link rel="shortcut icon" href="{% static 'home/icon/favicon.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'home/icon/apple-touch-icon-158-precomposed.png' %}">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% endblock %}

{% block body %}






<div class="row-services">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            </div>

            <div class="themesflat-headings style-1 clearfix text-justify padding-left-32" class="container"
                style="padding-top: 150px; color: black;">
                <h2 class="heading clearfix text-center">WHY US</h2>
                <div class=""></div>
                <p class="sub-heading clearfix" style="color:black; text-align: justify;">Founded by a
                    family with a long history in Real Estate and based in Texas, Quick
                    Commission Advance is dedicated to providing customized commission advance
                    services for residential real estate brokers and agents. We understand the
                    importance of cash flow to commission-based, real estate professionals. Here
                    at Quick Commission Advance we have set a goal of closing the gap between
                    signing the deal and closing transactions freeing you to grow your business.
                </p>
            </div><!-- /.themesflat-headings -->

            <div class="themesflat-spacer clearfix" data-desktop="50" data-mobi="40" data-smobi="40"></div>
        </div><!-- /.col-md-12 -->
    </div>
    <section>
        <div class="container-fluid"
            style="background-color:#f7f7f7; padding-top: 20px; padding-bottom: 10px;">
            <h3 class="text-left" style="color: #737373; margin-left: 160px;">WHAT IS COMMISSION  ADVANCE</h3>
        </div>
    </section>


    <div class="container">

        <img src="{% static 'home/img/imagebox/about1.jpeg' %}" alt="Image">

    </div>

    <section>
        <div class="container-fluid"
            style="background-color:#f7f7f7; padding-top: 20px; padding-bottom: 10px;">
            <h3 class="text-left" style="color: #737373; margin-left: 160px;">A FAST AND SIMPLE COMMISSION ADVANCE SOLUTION </h3>
        </div>
    </section>
    <div class="container">

        <img src="{% static 'home/img/about2.jpeg' %}" alt="Image">

    </div>
    <section>
        <div class="container-fluid"
            style="background-color:#f7f7f7
            ; padding-top: 20px; padding-bottom: 10px;">
            <h3 class="text-left" style="color: #737373; margin-left: 160px;">FAST & CONFDENTIAL PROCESS WITH NO CREDIT CHECK </h3>
        </div>
    </section>
    <div class="container">

        <img src="{% static 'home/img/imagebox/about3.jpeg' %}" alt="Image">

    </div>
    <section>
        <div class="container-fluid"
            style="background-color:#f7f7f7
            ; padding-top: 20px; padding-bottom: 10px; ;">
            <h3 class="text-left" style="color: #737373; margin-left: 160px;">HOW MUCH DOES IT COST?</h3>
        </div>
    </section>

    <div class="container">

        <img src="{% static 'home/img/imagebox/about4.jpeg' %}" alt="Image">

    </div>


    <div class="col-md-4">
        <div class="themesflat-image-box style-1 clearfix">
            <div class="item">
                <div class="inner">
                    <!-- <div class="text-wrap">
                                                    <div class="thumb"><img src="{% static 'home/img/imagebox/imagebox1.jpg' %}" alt="Image"></div>

                                                        <h3 class="title"><a target="_blank" href="">APPLY ONLINE</a></h3>

                                                        <div class="desc"> </div>
                                                    </div>-->
                </div>
            </div>
        </div><!-- /.themesflat-image-box -->

        <div class="themesflat-spacer clearfix" data-desktop="0" data-mobi="40" data-smobi="40"></div>
    </div><!-- /.col-md-4 -->

    <div class="col-md-4">
        <div class="themesflat-image-box style-1 clearfix">
            <div class="item">
                <!-- <div class="text-wrap">
                                                <div class="inner">
                                                    <div class="thumb"><img src="{% static 'home/img/imagebox/imagebox2.jpg' %}" alt="Image"></div>

                                                    <div class="text-wrap">
                                                        <h3 class="title"><a target="_blank" href="">PROJECT FINANCE</a></h3>

                                                        <div class="desc">Create a sustainable financing structure</div>
                                                    </div>
                                                </div>-->
            </div>
        </div><!-- /.themesflat-image-box -->

        <div class="themesflat-spacer clearfix" data-desktop="0" data-mobi="40" data-smobi="40"></div>
    </div><!-- /.col-md-4 -->

    <div class="col-md-4">
        <div class="themesflat-image-box style-1 clearfix">
            <div class="item">
                <div class="inner">
                    <!-- <div class="text-wrap">
                                                    <div class="thumb"><img src="{% static 'home/img/imagebox/imagebox3.jpg' %}" alt="Image"></div>

                                                    <div class="text-wrap">
                                                        <h3 class="title"><a target="_blank" href="">REAL ESTATE PLANNING</a></h3>

                                                        <div class="desc">How to finance your real estate investment</div>
                                                    </div>
                                                </div>-->
                </div>
            </div><!-- /.themesflat-image-box -->
        </div><!-- /.col-md-4 -->

        <div class="col-md-12">
            <div class="themesflat-spacer clearfix" data-desktop="90" data-mobi="60" data-smobi="60"></div>
        </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
</div><!-- /.container -->
</div>
<!-- END SERVICES IMAGEBOXS -->

{% endblock %}

templates/home/agentFaq.html
{% extends "home/base.html" %}
{% load static %}

{% block h %}
<!-- Basic Page Needs -->
<meta charset="utf-8">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<title>Quick Commission Advance</title>

<meta name="author" content="themesflat.com">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Theme Style -->
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

<!-- Favicon and Touch Icons  -->
<link rel="shortcut icon" href="{% static 'home/icon/favicon.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'home/icon/apple-touch-icon-158-precomposed.png' %}">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% endblock %}

{% block body %}

<section>
  <div class="container" style="padding-top: 160px;">
    <p class="sub-heading clearfix text-justify  " style="color:black">
      <h2 class="heading clearfix">AGENT FREQUENTLY ASKED QUESTIONS<br></h2>
      </p>
    <p align="left" style="color:black"> <b>When should I consider taking a
        commiission advance?</b><BR>
      Quick Commission Advance provides responsible, short term commission
      advances to help Realtors who are experiencing cash-flow challenges.
      We do this without running credit checks.
    </p>

    <p align="left" style="color:black"> <b>Who is eligible for commission
        advances?</b><BR>
      Quick Commission Advance serves licensed residential real estate
      agents who are affiliated with leading real estate companies across
      the United States.
    </p>

    <p align="left" style="color:black"> <b>What is the maximum amount you
        will advance?</b><BR>
      The maximum amount we will advance is $15,000.
    </p>

    <p align="left" style="color:black"> <b>How do you pay my advance to
        me?</b><BR>
      We will deposit your deposit directly into your bank account.
    </p>

    <p align="left" style="color:black"> <b>How long does it take to receive
        my commission advance?</b><BR>
      Typically, we'll provide same day approvals. In this instance, you
      will receive your advance within 24 hours
      after your commission advance is approved.
    </p>

    <p align="left" style="color:black"> <b>What types of contracts qualify
        foe a commission advance?</b><BR>
      Commissions from the sale of single-family residential properties,
      including town homes qualify for a commission advance.
    </p>
    <p align="left" style="color:black"> <b>At waht stage of the transaction
        can I advance my commission?</b><BR>
      We will advance you up to 80% of your commission.
    </p>
    <p align="left" style="color:black"> <b>Why only 30 days to
        close?</b><BR>
      Closings greater than 30 days carry significantly high risk. In
      order to provide advances quickly, with no credit checks or lengthy
      underwriting timeframes, we limit closings to 30 days.
    </p>
    <p align="left" style="color:black"> <b>Do you credit checks?</b><BR>
      No, we do not perform credit checks.
    </p>
    <p align="left" style="color:black"> <b>Will my request for a commission advance be confidential?</b><BR>
      Your commission advance transaction will be kept confidential between your broker and escrow adgent.
      We do not sell our customer's information.
    </p>
    <p align="left" style="color:black"> <b>Do you contact the Buyer or Seller?</b><BR>
      The buyer and or seller will not be contacted notified the transactions by us.
    </p>
    <p align="left" style="color:black"> <b>Does my broker need to register with Quick Commisssion?</b><BR>
      No, brokers do not have to register with QUick Commission, however, they are required to approve each advance
      request that an agent makes
      because all commissions ar legally owned by the broker. Therefore, we will not advance your commission without
      your broker's consent.
    </p>
    <p align="left" style="color:black"> <b>Is there liability for my broker?</b><BR>
      No, your broker does not bear any risk with a commission advance. You are solely responsible for the repayment of
      the commission advance. If the
      transaction fails through, you are responsible for replacing it with future earned commissions. The broker is
      responsible for directing any future earned commissions
      by the agent to Quick Commission Advance.
    </p>
    <p align="left" style="color:black"> <b>Can I have multiple advances at the same time?</b><BR>
      Yes, as long as you do not exceed advance limit of $15,000, you may take more than one advance at a time.
      Individual and multiple advances are subject to and limited by the underwriting process.
    </p>
    <p align="left" style="color:black"> <b>Do you have advance on short sales?</b><BR>
      No, we dont provide advances on a short sales.
    </p>
    <p align="left" style="color:black"> <b>Are there any application fees,wire transfer, or holding fees?</b><BR>
      There only is the advance fees described in the aggreement.
    </p>
    <p align="left" style="color:black"> <b>What happens if the sale fall through?</b><BR>
      A commission advance should only be taken responsibly, when you have other means to repay the advance in the
      unlikely event the sale were to cancel.
      This can be done simply by paying it off in full or in part, or by sending us a replacement contract to cover the
      canceled sale. If you choose to replace
      a canceled sale, you will be charges a new fee based on your original contract's advance fees.
    </p>
    <p align="left" style="color:black"> <b>Is there a minimum advance fees?</b><BR>
      Minimum advance fee is $400.
    </p>

    <p align="left" style="color:black"> <b>How is Quick Commission Advance repayed?</b><BR>
      The settlemet company directs payment of the applicable funds to Quick Commission Advance when the your sale
      closes. Your broker signs a disbursement authorization directing them to direct the portion
      of your commission purchased to Quick Commission Advance.<br><br>
    </p>

    <div class="themesflat-pagination padding-left-70 clearfix">
      <ul class="page-numbers">
          <li><a class="prev page-numbers" href="#"><span class=" finance-icon-cheveron-left"></span></a></li>
          <li><a class="page-numbers current"  href="{% url 'agent_Faq'%}">1</a></li>
          <li><a class="page-numbers " href="{% url 'broker_Faq'%}">2</a></li>
    
          <li><a class="next page-numbers" href="#"><span class=" finance-icon-cheveron-right"></span></a></li>
      </ul>
      <br>
    </div>
  </div>

  
</section>

{% endblock %}

templates/home/brokerFaq.html
{% extends "home/base.html" %}
{% load static %}

{% block h %}
<!-- Basic Page Needs -->
<meta charset="utf-8">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<title>Quick Commission Advance</title>

<meta name="author" content="themesflat.com">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Theme Style -->
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

<!-- Favicon and Touch Icons  -->
<link rel="shortcut icon" href="{% static 'home/icon/favicon.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'home/icon/apple-touch-icon-158-precomposed.png' %}">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% endblock %}

{% block body %}
<section>
  <div class="container" style="padding-top: 160px;">
    <p class="sub-heading clearfix text-justify " style="color:black">
      <h2 class="heading clearfix">BROKER FREQUENTLY ASKED QUESTIONS<br></h2></p>
    <p align="left" style="color:black"> <b>Why does the broker review and sign the advance agreement?</b><BR>
      Agents cannot advance commissions without the broker's consent. All commissions earned by your agents belong to
      your company. The agreement you sign authorizes the sale and
      assignment of the agent's portion of the commission on the subject sale to Quick Commission Advance, after any
      split or balance owing to your company.
    </p>

    <p align="left" style="color:black"> <b>How does this helps my agent?</b><BR>
      We help agents manage their cash flow to manage their professional expenses effectively and meet persoanl
      obligations. A commission advance alleviated financial distractions
      allowing the agent to focus on pursuing prospects or closing their next deal. Consider Quick Commission Advance as
      a partner you can count on to help your agents manage they when
      they get paid , keeping them motivated and engaged. The result is more listings, more sales and increased
      productivity.
    </p>

    <p align="left" style="color:black"> <b>Is there liability for the broker?</b><BR>
      No, your broker does not bear any risk with a commission advance. You are solely responsible for the repayment of
      the commission advance. If the transaction falls through, you are
      responsible for replacing it with future earned commissions. The Broker is responsible for directing any future
      earned commissions by the agent to Quick Commission Advance.
    </p>

    <p align="left" style="color:black"> <b>Are Broker Agents eligible for a commission advance?</b><BR>
      Yes, Quick Commission Advance will provide an advance to brokers acting as agents representing buyers or sellers on their own sales. Rates differ from agent rates.<br><br>
     </p>

<div class="themesflat-pagination padding-left-70 clearfix">
  <ul class="page-numbers">
      <li><a class="prev page-numbers" href="#"><span class=" finance-icon-cheveron-left"></span></a></li>
      <li><a class="page-numbers"  href="{% url 'agent_Faq'%}">1</a></li>
      <li><a class="page-numbers current" href="{% url 'broker_Faq'%}">2</a></li>

      <li><a class="next page-numbers" href="#"><span class=" finance-icon-cheveron-right"></span></a></li>
  </ul>
  <br>
</div>

</section>


{% endblock %}

templates/home/contactUs.html
{% extends "home/base.html" %}
{% load static %}

{% block h %}
<!-- Basic Page Needs -->
<meta charset="utf-8">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<title>Quick Commission Advance</title>

<meta name="author" content="themesflat.com">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Theme Style -->
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

<!-- Favicon and Touch Icons  -->
<link rel="shortcut icon" href="{% static 'home/icon/favicon.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'home/icon/apple-touch-icon-158-precomposed.png' %}">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% endblock %}

{% block body %}
<section>
    <div class="container" style="padding-top: 160px;">
    <h1>Contact Us</h1>
    </div>
    </section>

    <div class="row-request">
        <div class="container-fluid">
            <div class="row equalize sm-equalize-auto">
                
                <div class="col-md-6 bg-light-grey" style="margin-left: 400px;">
                    <div class="themesflat-spacer clearfix" data-desktop="85" data-mobi="40" data-smobi="40"></div>

                    <div class="themesflat-content-box clearfix " data-margin="0% 26.8% 0% 10.7%" data-mobimargin="0% 5% 0% 5%">
                        <div class="themesflat-headings style-3 clearfix">
                            <h2 class="heading clearfix">REQUEST FOR A CALL BACK</h2>
                            <div class="sep clearfix"></div>
                            <p class="sub-heading clearfix">Please complete this form, our expert advisor will be in touch with you.</p>
                        </div><!-- /.themesflat-headings -->

                        <div class="themesflat-spacer clearfix" data-desktop="32" data-mobi="40" data-smobi="40"></div>

                        <div class="themesflat-contact-form style-1">
                            <form action="./includes/contact/contact-process.php" method="post" class="contact-form wpcf7-form">
                                <span class="wpcf7-form-control-wrap your-name">
                                    <input type="text" tabindex="1" id="name" name="name" value="" class="wpcf7-form-control" placeholder="YOUR NAME*" required>
                                </span>
                                <span class="wpcf7-form-control-wrap your-phone">
                                    <input type="text" tabindex="2" id="phone" name="phone" value="" class="wpcf7-form-control" placeholder="YOUR PHONE*" required>
                                </span>
                                <span class="wpcf7-form-control-wrap your-subject">
                                    <input type="text" tabindex="3" id="subject" name="subject" value="" class="wpcf7-form-control" placeholder="SUBJECT*" required>
                                </span>
                                <span class="wpcf7-form-control-wrap your-message">
                                    <textarea name="message" tabindex="4" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" placeholder="YOUR MESSAGE*" required></textarea>
                                </span>
                                <div class="wrap-submit" style="text-align: center;">
                                    <input type="submit" value="CALL ME BACK" class="submit wpcf7-form-control wpcf7-submit" id="submit" name="submit">
                                </div>
                                
                            </form>
                        </div><!-- /.themesflat-contact-form -->
                    </div><!-- /.themesflat-content-box -->

                    <div class="themesflat-spacer clearfix" data-desktop="90" data-mobi="40" data-smobi="40"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}